### ISSUE TITLE
Weird log entries - miner no longer mining

### ISSUE THREAD

**Issue by Depechie** [simeononsecurity/docker-duino-coin#3]
Running the latest image I'm getting following log entries

```
2024-06-30 11:20:07 (8.24 MB/s) - ‘/app/duino-coin/Duino-Coin PC Miner 4.0/Donate.exe’ saved [1052672/1052672]
Traceback (most recent call last):
  File "/app/duino-coin/PC_Miner.py", line 1380, in <module>
    title(f"{get_string('duco_python_miner')}{str(Settings.VER)})")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/duino-coin/PC_Miner.py", line 707, in get_string
    if string_name in lang_file[lang]:
                      ~~~~~~~~~^^^^^^
KeyError: '"english"'
Extracted PC Miner VER value: 4.0
mkdir: cannot create directory ‘/app/duino-coin/Duino-Coin PC Miner 4.0’: File exists
```

I guess previous editions did not have the donation added?
Why is this needed and can we disable this?

**Comment by simeononsecurity** [comment]
> Running the latest image I'm getting following log entries
> 
> ```
> 2024-06-30 11:20:07 (8.24 MB/s) - ‘/app/duino-coin/Duino-Coin PC Miner 4.0/Donate.exe’ saved [1052672/1052672]
> Traceback (most recent call last):
>   File "/app/duino-coin/PC_Miner.py", line 1380, in <module>
>     title(f"{get_string('duco_python_miner')}{str(Settings.VER)})")
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/duino-coin/PC_Miner.py", line 707, in get_string
>     if string_name in lang_file[lang]:
>                       ~~~~~~~~~^^^^^^
> KeyError: '"english"'
> Extracted PC Miner VER value: 4.0
> mkdir: cannot create directory ‘/app/duino-coin/Duino-Coin PC Miner 4.0’: File exists
> ```
> 
> I guess previous editions did not have the donation added? Why is this needed and can we disable this?

Will investigate. Likely they changed something I didn't expect. This is why I wanted the docker container to be a part of the scripts repo but they rejected the mr.

**Comment by simeononsecurity** [comment]
@Depechie Try now.

**Comment by Depechie** [comment]
Still getting
```
2024-07-01 11:17:24 (8.21 MB/s) - ‘/app/duino-coin/Duino-Coin PC Miner 4.1/Donate.exe’ saved [1052672/1052672]
Traceback (most recent call last):
  File "/app/duino-coin/PC_Miner.py", line 1380, in <module>
    title(f"{get_string('duco_python_miner')}{str(Settings.VER)})")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/duino-coin/PC_Miner.py", line 707, in get_string
    if string_name in lang_file[lang]:
                      ~~~~~~~~~^^^^^^
KeyError: '"english"'
```

image sha256%3Ad404e381bc665a1be3a34067f2a544202d2eb84a3db4ebbc6866aea0aeb04158

**Comment by simeononsecurity** [comment]
> Still getting
> 
> ```
> 2024-07-01 11:17:24 (8.21 MB/s) - ‘/app/duino-coin/Duino-Coin PC Miner 4.1/Donate.exe’ saved [1052672/1052672]
> Traceback (most recent call last):
>   File "/app/duino-coin/PC_Miner.py", line 1380, in <module>
>     title(f"{get_string('duco_python_miner')}{str(Settings.VER)})")
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/duino-coin/PC_Miner.py", line 707, in get_string
>     if string_name in lang_file[lang]:
>                       ~~~~~~~~~^^^^^^
> KeyError: '"english"'
> ```
> 
> image sha256%3Ad404e381bc665a1be3a34067f2a544202d2eb84a3db4ebbc6866aea0aeb04158

Need you to make sure to delete that container, pull the latest image, and run the run command again

**Comment by Depechie** [comment]
![image](https://github.com/simeononsecurity/docker-duino-coin/assets/351693/eeba781c-1238-4e90-b2b7-3af140789dce)

<img width="895" alt="Screenshot 2024-07-02 at 13 34 50" src="https://github.com/simeononsecurity/docker-duino-coin/assets/351693/ebb2e182-c235-443f-84ff-ce4115959ae5">

No change, removed all image version I had and the container and added a new compose file with latest as image tag

**Comment by simeononsecurity** [comment]
> ![image](https://private-user-images.githubusercontent.com/351693/345004695-eeba781c-1238-4e90-b2b7-3af140789dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjExNTQsIm5iZiI6MTcxOTk2MDg1NCwicGF0aCI6Ii8zNTE2OTMvMzQ1MDA0Njk1LWVlYmE3ODFjLTEyMzgtNGU5MC1iMmI3LTNhZjE0MDc4OWRjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQyMjU0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmZiNTQwYTc5OTI3M2UxYTc3OGFiMWZhNDMzYTU1MWQxMzQyNmRhNTI0YWJkOGZhNWY0OTkyMWVkYWVhODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i6wHm-nweTMrN-R43jaifRmuWBiknfKGEwqLDDV0AcI)
> <img alt="Screenshot 2024-07-02 at 13 34 50" width="895" src="https://private-user-images.githubusercontent.com/351693/345004991-ebb2e182-c235-443f-84ff-ce4115959ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjExNTQsIm5iZiI6MTcxOTk2MDg1NCwicGF0aCI6Ii8zNTE2OTMvMzQ1MDA0OTkxLWViYjJlMTgyLWMyMzUtNDQzZi04NGZmLWNlNDExNTk1OWFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQyMjU0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzhiZjMwNmNkMTA4NDc4MDlkMzk0Y2M3MWYxMWJkYmE5ZjZlZjY0ODM4ZDNkNGI3YWU1MjBiNDcyYmNhNmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5fT9oBdhIZeCdHVUD0yhYFOdg3J2gDDXBmJ_7-EQWI">
> 
> No change, removed all image version I had and the container and added a new compose file with latest as image tag

That image hash doesn't match any of the ones released in the last couple days and I just tested the latest image again and it still works. 

Can you try doing the following after confirming again you've pulled the latest image?

```
version: '3'
services:
  duco-container:
    image: simeononsecurity/duinocoin:latest
    container_name: duco-container
    restart: unless-stopped
    environment:
      - DUCO_USERNAME=your_actual_username_or_walletname
      - DUCO_MINING_KEY=your_actual_mining_key
      - DUCO_INTENSITY=50 
      - DUCO_THREADS=2 
      - DUCO_START_DIFF=MEDIUM 
      - DUCO_DONATE=1 
      - DUCO_IDENTIFIER=Auto 
      - DUCO_ALGORITHM=DUCO-S1 
      - DUCO_LANGUAGE=english  # Adjusted the language key if needed
      - DUCO_SOC_TIMEOUT=20 
      - DUCO_REPORT_SEC=300 
      - DUCO_RASPI_LEDS=n 
      - DUCO_RASPI_CPU_IOT=n 
      - DUCO_DISCORD_RP=n
```

**Comment by Depechie** [comment]
That docker compose does indeed seem to work, still not sure what the difference was with mine. But now it's working again, thx.
